kind: ConfigMap
apiVersion: v1
metadata:
  name: emqtt-cluster
  namespace: default
data:
  EMQ_NAME: "emqtt"
  EMQ_CLUSTER__DISCOVERY: "k8s"
  EMQ_CLUSTER__K8S__APISERVER: "https://kubernetes.default:443"
  EMQ_CLUSTER__K8S__NAMESPACE: "default"
  EMQ_CLUSTER__K8S__SERVICE_NAME: "emqtt"
  EMQ_CLUSTER__K8S__ADDRESS_TYPE: "ip"
  EMQ_CLUSTER__K8S__APP_NAME: "emqtt"
  EMQ_CLUSTER__NAME: "emqcl"
  EMQ_CLUSTER__AUTOHEAL: "on"
  EMQ_CLUSTER__AUTOCLEAN: "5m"
  EMQ_LISTENER__WS__EXTERNAL__PROXY_PROTOCOL: "off"
  EMQ_LISTENER__WSS__EXTERNAL__PROXY_PROTOCOL: "off"
  #EMQ_LOADED_PLUGINS: "emqx_auth_http,emqx_recon,emqx_management,emqx_dashboard"
  EMQ_LOADED_PLUGINS: "emq_recon,emq_modules,emq_dashboard,emq_auth_http"
  EMQ_LISTENER__TCP__INTERNAL__MAX_CLIENTS: "10"
  EMQ_LISTENER__TCP__EXTERNAL__MAX_CLIENTS: "10000"
  EMQ_LISTENER__WS__EXTERNAL__MAX_CLIENTS: "10000"
  EMQ_LISTENER__WS__EXTERNAL__MQTT_PATH: "/ws"
  EMQ_LISTENER__SSL__EXTERNAL__MAX_CLIENTS: "10"
  EMQ_ZONE__EXTERNAL__MQUEUE__STORE__QOS0: "false"
  EMQ_ZONE__INTERNAL__MQUEUE__STORE__QOS0: "false"
  EMQ_MQTT__RETAIN__AVAILABLE: "true"
  EMQ_MQTT__MAX_PACKET_SIZE: "25MB"
  EMQ_ZONE__EXTERNAL__RETAIN_AVAILABLE: "true"
  EMQ_AUTH__HTTP__AUTH_REQ: "http://auth-api/mqtt/auth"
  EMQ_AUTH__HTTP__SUPER_REQ: "http://auth-api/mqtt/superuser"
  EMQ_AUTH__HTTP__ACL_REQ: "http://auth-api/mqtt/acl"
  EMQ_AUTH__HTTP__AUTH__REQ__PARAMS: "clientid=%c,username=%u,password=%P"
  EMQ_AUTH__HTTP__SUPER_REQ__PARAMS: "clientid=%c,username=%u"
  EMQ_AUTH__HTTP__ACL_REQ__PARAMS: "access=%A,username=%u,clientid=%c,ipaddr=%a,topic=%t"
---
kind: Secret
apiVersion: v1
metadata:
  name: emqtt-cluster
  namespace: default
type: Opaque
data:
  EMQ_NODE__COOKIE: TkdRMFZUUnlTRzlNVm05MGNHTkY=